from langchain.chains import RetrievalQA, LLMChain

class GeneralLangChainRetrievalQA: 
    def set_retrieval_qa_chain(self, llm, retriever):
        self.chain = RetrievalQA.from_chain_type(
            llm=llm,
            chain_type="stuff",
            retriever=retriever,
            return_source_documents=True
        )

    def run_basic_query(self, query):
        """Run the RetrievalQA chain with the given query.
        Args:
            query (str): The input query to be answered.
        Returns:
            The answer generated by the chain.
        Example:
            ```python
            response = chain.run_basic_query("What is the capital of France?")
            print(response)
            # Output: "The capital of France is Paris."
            ```
        """
        return self.chain.run({"query": query})